= Liste vorbereiten

== Randbedingungen
Gesamtmenge Tupel: *483* + 
Gesamtmenge Attribute: *23* + 
Menge Ziel-Attribute: *7*

== Ablauf

. Zufällig Menge der Ziel-Tupel berechnen (70 - 150)
. Für jedes Ziel-Tupel ein zufälliges Original-Tupel (1 - 483) ziehen. Achtung: _Jedes 
    darf nur einmal vorkommen!_ + 
    Ergebnis: Eine Liste von 70-150 Zeilennummern zwischen 1 und 483.
. Für jedes Ziel-Attribut ein zufälliges Original-Attribut (1 - 23) ziehen.
    Achtung: _Jedes darf nur einmal vorkommen!_ + 
    Ergebnis: Eine Liste von 7 Spaltennummern zwischen 1 und 23.
. Eingabedatei und Ausgabedatei öffnen
. Eingabedatei zeilenweise lesen
.. Jede Zeile, die als Original-Tupel markiert wurde, auseinanderbauen am 
    Trennzeichen
.. Jeden Wert für ein Ziel-Attribut dieser Zeile in eine neue Zeichenkette 
    überführen (= neues Tupel generieren)
.. Generierte Zeile in Ausgabedatei schreiben
. Dateien schließen
. Fertisch!

=== Eckpunkte
* 2 Listen, die auf ähnliche Weise erzeugt werden
* In Liste suchen
* Mehrere Zufallszahlen (Bereich x bis y)
* Datei lesen/schreiben
* String zerlegen

== Was braucht man grob in C++ ?
* fstream -> ifstream, ofstream
* string
* vector
* algorithm -> std::find, 
* cstdlib, time.h -> srand, rand
* cstring -> strtok

[source,cpp]
.String auseinanderbauen und zusammenfügen
----
const char* s = "erster;zweiter;dritter";
char* t = new char[strlen(s) + 1];
strcpy(t, s);
vector<const char*> v;

// Tokenize t into v
char* tmp = strtok(t, ";");
while (tmp) {
    v.push_back(tmp);
    tmp = strtok(0, ";");
}

// Output concatenated
for (auto it = v.begin(); it != v.end(); ++it) {
    cout << *it;
    if ((it + 1) != v.end()) {
        cout << ";";
    }
}
cout << endl;
----

[source,cpp]
.Element in Vektor enthalten?
----
vector<string> v;
//...
string element("hallo");

auto it = std::find(v.begin(), v.end(), element);
if (it != v.end()) {
    // Gefunden
} else {
    // Nicht gefunden
}
----
