/* Copyright (C) 2014 Maurice Bleuel, Jan Siegert
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package infoint.aufgabe1.dbcreate;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import com.bleuelmedia.javatools.logging.Log;

public class Database {

	//==========================================================================
	// CLASS MEMBERS
	
	public static final String TAG = "Database";
	
	//==========================================================================
	// CLASS METHODS
	
	//==========================================================================
	// INSTANCE MEMBERS
	
	private File dbFile;
	private Connection connection;
	private boolean open;
	
	public Database(String path) {
		dbFile = new File(path);
	}
	
	public void open() {
		boolean create = (dbFile.exists()) ? false : true;
		
		try {
			connection = DriverManager.getConnection("jdbc:sqlite:" + dbFile.getAbsolutePath());
			open = true;
			if (create) {
				createDatabase();
			}
		} catch (SQLException ex) {
			Log.e(TAG, "Failed to open database at '" + dbFile.getAbsolutePath() + "'");
			return;
		}
	}
	
	public void close() {
		if (!open) {
			return;
		}
		
		try {
			connection.close();
		} catch (SQLException ex) {
			Log.e(TAG, "Failed to close database: " + ex.getMessage());
			System.exit(1);
		}
		open = false;
	}
	
	public PreparedStatement prepare(String sql) throws SQLException {
		return connection.prepareStatement(sql);
	}
	
	public Statement createStatement() throws SQLException {
		return connection.createStatement();
	}
	
	private boolean createDatabase() {
		try {
			Statement st = connection.createStatement();
			
			st.addBatch("BEGIN TRANSACTION;");
			st.addBatch("CREATE TABLE \"names\" "
					+ "(\"id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "
					+ "\"name\" TEXT NOT NULL, "
					+ "\"fullname\" TEXT NOT NULL, "
					+ "\"country\" TEXT NOT NULL);");
			st.addBatch("CREATE TABLE \"qgrams\" "
					+ "(\"id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "
					+ "\"qgram\" TEXT NOT NULL, "
					+ "\"names_id\" INTEGER NOT NULL);");
			st.addBatch("CREATE TABLE \"countries\" "
					+ "(\"code\" TEXT NOT NULL,"
					+ "\"name\" TEXT NOT NULL)");
			st.addBatch("INSERT INTO \"countries\" VALUES('AD','Andorra');"
					+ "INSERT INTO \"countries\" VALUES('AE','Vereinigte Arabische Emirate');"
					+ "INSERT INTO \"countries\" VALUES('AF','Afghanistan');"
					+ "INSERT INTO \"countries\" VALUES('AG','Antigua und Barbuda');"
					+ "INSERT INTO \"countries\" VALUES('AI','Anguilla');"
					+ "INSERT INTO \"countries\" VALUES('AL','Albanien');"
					+ "INSERT INTO \"countries\" VALUES('AM','Armenien');"
					+ "INSERT INTO \"countries\" VALUES('AO','Angola');"
					+ "INSERT INTO \"countries\" VALUES('AQ','Antarktis');"
					+ "INSERT INTO \"countries\" VALUES('AR','Argentinien');"
					+ "INSERT INTO \"countries\" VALUES('AS','Amerikanisch-Samoa');"
					+ "INSERT INTO \"countries\" VALUES('AT','Österreich');"
					+ "INSERT INTO \"countries\" VALUES('AU','Australien');"
					+ "INSERT INTO \"countries\" VALUES('AW','Aruba');"
					+ "INSERT INTO \"countries\" VALUES('AX','Ålandinseln');"
					+ "INSERT INTO \"countries\" VALUES('AZ','Aserbaidschan');"
					+ "INSERT INTO \"countries\" VALUES('BA','Bosnien und Herzegowina');"
					+ "INSERT INTO \"countries\" VALUES('BB','Barbados');"
					+ "INSERT INTO \"countries\" VALUES('BD','Bangladesch');"
					+ "INSERT INTO \"countries\" VALUES('BE','Belgien');"
					+ "INSERT INTO \"countries\" VALUES('BF','Burkina Faso');"
					+ "INSERT INTO \"countries\" VALUES('BG','Bulgarien');"
					+ "INSERT INTO \"countries\" VALUES('BH','Bahrain');"
					+ "INSERT INTO \"countries\" VALUES('BI','Burundi');"
					+ "INSERT INTO \"countries\" VALUES('BJ','Benin');"
					+ "INSERT INTO \"countries\" VALUES('BL','St. Barthélemy');"
					+ "INSERT INTO \"countries\" VALUES('BM','Bermuda');"
					+ "INSERT INTO \"countries\" VALUES('BN','Brunei Darussalam');"
					+ "INSERT INTO \"countries\" VALUES('BO','Bolivien');"
					+ "INSERT INTO \"countries\" VALUES('BR','Brasilien');"
					+ "INSERT INTO \"countries\" VALUES('BS','Bahamas');"
					+ "INSERT INTO \"countries\" VALUES('BT','Bhutan');"
					+ "INSERT INTO \"countries\" VALUES('BV','Bouvetinsel');"
					+ "INSERT INTO \"countries\" VALUES('BW','Botsuana');"
					+ "INSERT INTO \"countries\" VALUES('BY','Belarus');"
					+ "INSERT INTO \"countries\" VALUES('BZ','Belize');"
					+ "INSERT INTO \"countries\" VALUES('CA','Kanada');"
					+ "INSERT INTO \"countries\" VALUES('CC','Kokosinseln');"
					+ "INSERT INTO \"countries\" VALUES('CD','Demokratische Republik Kongo');"
					+ "INSERT INTO \"countries\" VALUES('CF','Zentralafrikanische Republik');"
					+ "INSERT INTO \"countries\" VALUES('CG','Republik Kongo');"
					+ "INSERT INTO \"countries\" VALUES('CH','Schweiz');"
					+ "INSERT INTO \"countries\" VALUES('CI','Côte d’Ivoire');"
					+ "INSERT INTO \"countries\" VALUES('CK','Cookinseln');"
					+ "INSERT INTO \"countries\" VALUES('CL','Chile');"
					+ "INSERT INTO \"countries\" VALUES('CM','Kamerun');"
					+ "INSERT INTO \"countries\" VALUES('CN','China');"
					+ "INSERT INTO \"countries\" VALUES('CO','Kolumbien');"
					+ "INSERT INTO \"countries\" VALUES('CP','Clipperton');"
					+ "INSERT INTO \"countries\" VALUES('CR','Costa Rica');"
					+ "INSERT INTO \"countries\" VALUES('CU','Kuba');"
					+ "INSERT INTO \"countries\" VALUES('CV','Kap Verde');"
					+ "INSERT INTO \"countries\" VALUES('CX','Weihnachtsinsel');"
					+ "INSERT INTO \"countries\" VALUES('CW','Curaçao');"
					+ "INSERT INTO \"countries\" VALUES('CY','Zypern');"
					+ "INSERT INTO \"countries\" VALUES('CZ','Tschechische Republik');"
					+ "INSERT INTO \"countries\" VALUES('DE','Deutschland');"
					+ "INSERT INTO \"countries\" VALUES('DJ','Dschibuti');"
					+ "INSERT INTO \"countries\" VALUES('DK','Dänemark');"
					+ "INSERT INTO \"countries\" VALUES('DM','Dominica');"
					+ "INSERT INTO \"countries\" VALUES('DO','Dominikanische Republik');"
					+ "INSERT INTO \"countries\" VALUES('DZ','Algerien');"
					+ "INSERT INTO \"countries\" VALUES('EC','Ecuador');"
					+ "INSERT INTO \"countries\" VALUES('EE','Estland');"
					+ "INSERT INTO \"countries\" VALUES('EG','Ägypten');"
					+ "INSERT INTO \"countries\" VALUES('EH','Westsahara');"
					+ "INSERT INTO \"countries\" VALUES('EL','Griechenland');"
					+ "INSERT INTO \"countries\" VALUES('ER','Eritrea');"
					+ "INSERT INTO \"countries\" VALUES('ES','Spanien');"
					+ "INSERT INTO \"countries\" VALUES('ET','Äthiopien');"
					+ "INSERT INTO \"countries\" VALUES('FI','Finnland');"
					+ "INSERT INTO \"countries\" VALUES('FJ','Fidschi');"
					+ "INSERT INTO \"countries\" VALUES('FK','Falklandinseln (Malwinen)');"
					+ "INSERT INTO \"countries\" VALUES('FM','Mikronesien');"
					+ "INSERT INTO \"countries\" VALUES('FO','Färöer');"
					+ "INSERT INTO \"countries\" VALUES('FR','Frankreich');"
					+ "INSERT INTO \"countries\" VALUES('XX','ehemalige jugoslawische Republik Mazedonien');"
					+ "INSERT INTO \"countries\" VALUES('GA','Gabun');"
					+ "INSERT INTO \"countries\" VALUES('GD','Grenada');"
					+ "INSERT INTO \"countries\" VALUES('GE','Georgien');"
					+ "INSERT INTO \"countries\" VALUES('GF','Französisch-Guayana');"
					+ "INSERT INTO \"countries\" VALUES('GG','Guernsey');"
					+ "INSERT INTO \"countries\" VALUES('GH','Ghana');"
					+ "INSERT INTO \"countries\" VALUES('GI','Gibraltar');"
					+ "INSERT INTO \"countries\" VALUES('GL','Grönland');"
					+ "INSERT INTO \"countries\" VALUES('GM','Gambia');"
					+ "INSERT INTO \"countries\" VALUES('GN','Guinea');"
					+ "INSERT INTO \"countries\" VALUES('GP','Guadeloupe');"
					+ "INSERT INTO \"countries\" VALUES('GQ','Äquatorialguinea');"
					+ "INSERT INTO \"countries\" VALUES('GS','Südgeorgien und die Südlichen Sandwichinseln');"
					+ "INSERT INTO \"countries\" VALUES('GT','Guatemala');"
					+ "INSERT INTO \"countries\" VALUES('GU','Guam');"
					+ "INSERT INTO \"countries\" VALUES('GW','Guinea-Bissau');"
					+ "INSERT INTO \"countries\" VALUES('GY','Guyana');"
					+ "INSERT INTO \"countries\" VALUES('HK','Hongkong');"
					+ "INSERT INTO \"countries\" VALUES('HM','Heard und die McDonaldinseln');"
					+ "INSERT INTO \"countries\" VALUES('HN','Honduras');"
					+ "INSERT INTO \"countries\" VALUES('HR','Kroatien');"
					+ "INSERT INTO \"countries\" VALUES('HT','Haiti');"
					+ "INSERT INTO \"countries\" VALUES('HU','Ungarn');"
					+ "INSERT INTO \"countries\" VALUES('ID','Indonesien');"
					+ "INSERT INTO \"countries\" VALUES('IE','Irland');"
					+ "INSERT INTO \"countries\" VALUES('IL','Israel');"
					+ "INSERT INTO \"countries\" VALUES('IM','Insel Man');"
					+ "INSERT INTO \"countries\" VALUES('IN','Indien');"
					+ "INSERT INTO \"countries\" VALUES('IO','Britisches Territorium im Indischen Ozean');"
					+ "INSERT INTO \"countries\" VALUES('IQ','Irak');"
					+ "INSERT INTO \"countries\" VALUES('IR','Iran');"
					+ "INSERT INTO \"countries\" VALUES('IS','Island');"
					+ "INSERT INTO \"countries\" VALUES('IT','Italien');"
					+ "INSERT INTO \"countries\" VALUES('JE','Jersey');"
					+ "INSERT INTO \"countries\" VALUES('JM','Jamaika');"
					+ "INSERT INTO \"countries\" VALUES('JO','Jordanien');"
					+ "INSERT INTO \"countries\" VALUES('JP','Japan');"
					+ "INSERT INTO \"countries\" VALUES('KE','Kenia');"
					+ "INSERT INTO \"countries\" VALUES('KG','Kirgisistan');"
					+ "INSERT INTO \"countries\" VALUES('KH','Kambodscha');"
					+ "INSERT INTO \"countries\" VALUES('KI','Kiribati');"
					+ "INSERT INTO \"countries\" VALUES('KM','Komoren');"
					+ "INSERT INTO \"countries\" VALUES('KN','St. Kitts und Nevis');"
					+ "INSERT INTO \"countries\" VALUES('KP','Nordkorea');"
					+ "INSERT INTO \"countries\" VALUES('KR','Südkorea');"
					+ "INSERT INTO \"countries\" VALUES('KW','Kuwait');"
					+ "INSERT INTO \"countries\" VALUES('KY','Kaimaninseln');"
					+ "INSERT INTO \"countries\" VALUES('KZ','Kasachstan');"
					+ "INSERT INTO \"countries\" VALUES('LA','Demokratische Volksrepublik Laos');"
					+ "INSERT INTO \"countries\" VALUES('LB','Libanon');"
					+ "INSERT INTO \"countries\" VALUES('LC','St. Lucia');"
					+ "INSERT INTO \"countries\" VALUES('LI','Liechtenstein');"
					+ "INSERT INTO \"countries\" VALUES('LK','Sri Lanka');"
					+ "INSERT INTO \"countries\" VALUES('LR','Liberia');"
					+ "INSERT INTO \"countries\" VALUES('LS','Lesotho');"
					+ "INSERT INTO \"countries\" VALUES('LT','Litauen');"
					+ "INSERT INTO \"countries\" VALUES('LU','Luxemburg');"
					+ "INSERT INTO \"countries\" VALUES('LV','Lettland');"
					+ "INSERT INTO \"countries\" VALUES('LY','Libyen');"
					+ "INSERT INTO \"countries\" VALUES('MA','Marokko');"
					+ "INSERT INTO \"countries\" VALUES('MC','Monaco');"
					+ "INSERT INTO \"countries\" VALUES('MD','Moldau');"
					+ "INSERT INTO \"countries\" VALUES('ME','Montenegro');"
					+ "INSERT INTO \"countries\" VALUES('MF','St. Martin');"
					+ "INSERT INTO \"countries\" VALUES('MG','Madagaskar');"
					+ "INSERT INTO \"countries\" VALUES('MH','Marshallinseln');"
					+ "INSERT INTO \"countries\" VALUES('ML','Mali');"
					+ "INSERT INTO \"countries\" VALUES('MM','Myanmar/Birma');"
					+ "INSERT INTO \"countries\" VALUES('MN','Mongolei');"
					+ "INSERT INTO \"countries\" VALUES('MO','Macau');"
					+ "INSERT INTO \"countries\" VALUES('MP','Nördliche Marianen');"
					+ "INSERT INTO \"countries\" VALUES('MQ','Martinique');"
					+ "INSERT INTO \"countries\" VALUES('MR','Mauretanien');"
					+ "INSERT INTO \"countries\" VALUES('MS','Montserrat');"
					+ "INSERT INTO \"countries\" VALUES('MT','Malta');"
					+ "INSERT INTO \"countries\" VALUES('MU','Mauritius');"
					+ "INSERT INTO \"countries\" VALUES('MV','Malediven');"
					+ "INSERT INTO \"countries\" VALUES('MW','Malawi');"
					+ "INSERT INTO \"countries\" VALUES('MX','Mexiko');"
					+ "INSERT INTO \"countries\" VALUES('MY','Malaysia');"
					+ "INSERT INTO \"countries\" VALUES('MZ','Mosambik');"
					+ "INSERT INTO \"countries\" VALUES('NA','Namibia');"
					+ "INSERT INTO \"countries\" VALUES('NC','Neukaledonien');"
					+ "INSERT INTO \"countries\" VALUES('NE','Niger');"
					+ "INSERT INTO \"countries\" VALUES('NF','Norfolkinsel');"
					+ "INSERT INTO \"countries\" VALUES('NG','Nigeria');"
					+ "INSERT INTO \"countries\" VALUES('NI','Nicaragua');"
					+ "INSERT INTO \"countries\" VALUES('NL','Niederlande');"
					+ "INSERT INTO \"countries\" VALUES('NO','Norwegen');"
					+ "INSERT INTO \"countries\" VALUES('NP','Nepal');"
					+ "INSERT INTO \"countries\" VALUES('NR','Nauru');"
					+ "INSERT INTO \"countries\" VALUES('NU','Niue');"
					+ "INSERT INTO \"countries\" VALUES('NZ','Neuseeland');"
					+ "INSERT INTO \"countries\" VALUES('OM','Oman');"
					+ "INSERT INTO \"countries\" VALUES('PA','Panama');"
					+ "INSERT INTO \"countries\" VALUES('PE','Peru');"
					+ "INSERT INTO \"countries\" VALUES('PF','Französisch-Polynesien');"
					+ "INSERT INTO \"countries\" VALUES('PG','Papua-Neuguinea');"
					+ "INSERT INTO \"countries\" VALUES('PH','Philippinen');"
					+ "INSERT INTO \"countries\" VALUES('PK','Pakistan');"
					+ "INSERT INTO \"countries\" VALUES('PL','Polen');"
					+ "INSERT INTO \"countries\" VALUES('PM','St. Pierre und Miquelon');"
					+ "INSERT INTO \"countries\" VALUES('PN','Pitcairninseln');"
					+ "INSERT INTO \"countries\" VALUES('PR','Puerto Rico');"
					+ "INSERT INTO \"countries\" VALUES('PT','Portugal');"
					+ "INSERT INTO \"countries\" VALUES('PW','Palau');"
					+ "INSERT INTO \"countries\" VALUES('PY','Paraguay');"
					+ "INSERT INTO \"countries\" VALUES('QA','Katar');"
					+ "INSERT INTO \"countries\" VALUES('RE','Réunion');"
					+ "INSERT INTO \"countries\" VALUES('RO','Rumänien');"
					+ "INSERT INTO \"countries\" VALUES('RS','Serbien');"
					+ "INSERT INTO \"countries\" VALUES('RU','Russland');"
					+ "INSERT INTO \"countries\" VALUES('RW','Ruanda');"
					+ "INSERT INTO \"countries\" VALUES('SA','Saudi-Arabien');"
					+ "INSERT INTO \"countries\" VALUES('SB','Salomonen');"
					+ "INSERT INTO \"countries\" VALUES('SC','Seychellen');"
					+ "INSERT INTO \"countries\" VALUES('SD','Sudan');"
					+ "INSERT INTO \"countries\" VALUES('SE','Schweden');"
					+ "INSERT INTO \"countries\" VALUES('SG','Singapur');"
					+ "INSERT INTO \"countries\" VALUES('SH','St. Helena, Ascension und Tristan da Cunha');"
					+ "INSERT INTO \"countries\" VALUES('SI','Slowenien');"
					+ "INSERT INTO \"countries\" VALUES('SJ','Svalbard und Jan Mayen');"
					+ "INSERT INTO \"countries\" VALUES('SK','Slowakei');"
					+ "INSERT INTO \"countries\" VALUES('SL','Sierra Leone');"
					+ "INSERT INTO \"countries\" VALUES('SM','San Marino');"
					+ "INSERT INTO \"countries\" VALUES('SN','Senegal');"
					+ "INSERT INTO \"countries\" VALUES('SO','Somalia');"
					+ "INSERT INTO \"countries\" VALUES('SR','Suriname');"
					+ "INSERT INTO \"countries\" VALUES('SS','Südsudan');"
					+ "INSERT INTO \"countries\" VALUES('ST','São Tomé und Príncipe');"
					+ "INSERT INTO \"countries\" VALUES('SV','El Salvador');"
					+ "INSERT INTO \"countries\" VALUES('SX','St. Martin');"
					+ "INSERT INTO \"countries\" VALUES('SY','Syrien');"
					+ "INSERT INTO \"countries\" VALUES('SZ','Swasiland');"
					+ "INSERT INTO \"countries\" VALUES('TC','Turks- und Caicosinseln');"
					+ "INSERT INTO \"countries\" VALUES('TD','Tschad');"
					+ "INSERT INTO \"countries\" VALUES('TF','Französische Süd- und Antarktisgebiete');"
					+ "INSERT INTO \"countries\" VALUES('TG','Togo');"
					+ "INSERT INTO \"countries\" VALUES('TH','Thailand');"
					+ "INSERT INTO \"countries\" VALUES('TJ','Tadschikistan');"
					+ "INSERT INTO \"countries\" VALUES('TK','Tokelau');"
					+ "INSERT INTO \"countries\" VALUES('TL','Timor-Leste');"
					+ "INSERT INTO \"countries\" VALUES('TM','Turkmenistan');"
					+ "INSERT INTO \"countries\" VALUES('TN','Tunesien');"
					+ "INSERT INTO \"countries\" VALUES('TO','Tonga');"
					+ "INSERT INTO \"countries\" VALUES('TR','Türkei');"
					+ "INSERT INTO \"countries\" VALUES('TT','Trinidad und Tobago');"
					+ "INSERT INTO \"countries\" VALUES('TV','Tuvalu');"
					+ "INSERT INTO \"countries\" VALUES('TW','Taiwan');"
					+ "INSERT INTO \"countries\" VALUES('TZ','Tansania');"
					+ "INSERT INTO \"countries\" VALUES('UA','Ukraine');"
					+ "INSERT INTO \"countries\" VALUES('UG','Uganda');"
					+ "INSERT INTO \"countries\" VALUES('UK','Vereinigtes Königreich');"
					+ "INSERT INTO \"countries\" VALUES('UM','Kleinere Amerikanische Überseeinseln');"
					+ "INSERT INTO \"countries\" VALUES('US','Vereinigte Staaten');"
					+ "INSERT INTO \"countries\" VALUES('UY','Uruguay');"
					+ "INSERT INTO \"countries\" VALUES('UZ','Usbekistan');"
					+ "INSERT INTO \"countries\" VALUES('VA','Heiliger Stuhl/Vatikanstadt');"
					+ "INSERT INTO \"countries\" VALUES('VC','St. Vincent und die Grenadinen');"
					+ "INSERT INTO \"countries\" VALUES('VE','Venezuela');"
					+ "INSERT INTO \"countries\" VALUES('VG','Britische Jungferninseln');"
					+ "INSERT INTO \"countries\" VALUES('VI','Amerikanische Jungferninseln');"
					+ "INSERT INTO \"countries\" VALUES('VN','Vietnam');"
					+ "INSERT INTO \"countries\" VALUES('VU','Vanuatu');"
					+ "INSERT INTO \"countries\" VALUES('WF','Wallis und Futuna');"
					+ "INSERT INTO \"countries\" VALUES('WS','Samoa');"
					+ "INSERT INTO \"countries\" VALUES('YE','Jemen');"
					+ "INSERT INTO \"countries\" VALUES('YT','Mayotte');"
					+ "INSERT INTO \"countries\" VALUES('ZA','Südafrika');"
					+ "INSERT INTO \"countries\" VALUES('ZM','Sambia');"
					+ "INSERT INTO \"countries\" VALUES('ZW','Simbabwe');"
					+ "INSERT INTO \"countries\" VALUES('AF','AFGHANISTAN');"
					+ "INSERT INTO \"countries\" VALUES('AL','ALBANIA');"
					+ "INSERT INTO \"countries\" VALUES('DZ','ALGERIA');"
					+ "INSERT INTO \"countries\" VALUES('AS','AMERICAN SAMOA');"
					+ "INSERT INTO \"countries\" VALUES('AD','ANDORRA');"
					+ "INSERT INTO \"countries\" VALUES('AO','ANGOLA');"
					+ "INSERT INTO \"countries\" VALUES('AI','ANGUILLA');"
					+ "INSERT INTO \"countries\" VALUES('AQ','ANTARCTICA');"
					+ "INSERT INTO \"countries\" VALUES('AG','ANTIGUA AND BARBUDA');"
					+ "INSERT INTO \"countries\" VALUES('AR','ARGENTINA');"
					+ "INSERT INTO \"countries\" VALUES('AM','ARMENIA');"
					+ "INSERT INTO \"countries\" VALUES('AW','ARUBA');"
					+ "INSERT INTO \"countries\" VALUES('AU','AUSTRALIA');"
					+ "INSERT INTO \"countries\" VALUES('AT','AUSTRIA');"
					+ "INSERT INTO \"countries\" VALUES('AZ','AZERBAIJAN');"
					+ "INSERT INTO \"countries\" VALUES('BS','BAHAMAS');"
					+ "INSERT INTO \"countries\" VALUES('BH','BAHRAIN');"
					+ "INSERT INTO \"countries\" VALUES('BD','BANGLADESH');"
					+ "INSERT INTO \"countries\" VALUES('BB','BARBADOS');"
					+ "INSERT INTO \"countries\" VALUES('BY','BELARUS');"
					+ "INSERT INTO \"countries\" VALUES('BE','BELGIUM');"
					+ "INSERT INTO \"countries\" VALUES('BZ','BELIZE');"
					+ "INSERT INTO \"countries\" VALUES('BJ','BENIN');"
					+ "INSERT INTO \"countries\" VALUES('BM','BERMUDA');"
					+ "INSERT INTO \"countries\" VALUES('BT','BHUTAN');"
					+ "INSERT INTO \"countries\" VALUES('BO','BOLIVIA');"
					+ "INSERT INTO \"countries\" VALUES('BA','BOSNIA AND HERZEGOWINA');"
					+ "INSERT INTO \"countries\" VALUES('BW','BOTSWANA');"
					+ "INSERT INTO \"countries\" VALUES('BV','BOUVET ISLAND');"
					+ "INSERT INTO \"countries\" VALUES('BR','BRAZIL');"
					+ "INSERT INTO \"countries\" VALUES('IO','BRITISH INDIAN OCEAN TERRITORY');"
					+ "INSERT INTO \"countries\" VALUES('BN','BRUNEI DARUSSALAM');"
					+ "INSERT INTO \"countries\" VALUES('BG','BULGARIA');"
					+ "INSERT INTO \"countries\" VALUES('BF','BURKINA FASO');"
					+ "INSERT INTO \"countries\" VALUES('BI','BURUNDI');"
					+ "INSERT INTO \"countries\" VALUES('KH','CAMBODIA');"
					+ "INSERT INTO \"countries\" VALUES('CM','CAMEROON');"
					+ "INSERT INTO \"countries\" VALUES('CA','CANADA');"
					+ "INSERT INTO \"countries\" VALUES('CV','CAPE VERDE');"
					+ "INSERT INTO \"countries\" VALUES('KY','CAYMAN ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('CF','CENTRAL AFRICAN REPUBLIC');"
					+ "INSERT INTO \"countries\" VALUES('TD','CHAD');"
					+ "INSERT INTO \"countries\" VALUES('CL','CHILE');"
					+ "INSERT INTO \"countries\" VALUES('CN','CHINA');"
					+ "INSERT INTO \"countries\" VALUES('CX','CHRISTMAS ISLAND');"
					+ "INSERT INTO \"countries\" VALUES('CC','COCOS (KEELING) ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('CO','COLOMBIA');"
					+ "INSERT INTO \"countries\" VALUES('KM','COMOROS');"
					+ "INSERT INTO \"countries\" VALUES('CG','CONGO');"
					+ "INSERT INTO \"countries\" VALUES('CD','CONGO, THE DRC');"
					+ "INSERT INTO \"countries\" VALUES('CK','COOK ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('CR','COSTA RICA');"
					+ "INSERT INTO \"countries\" VALUES('CI','COTE D''IVOIRE');"
					+ "INSERT INTO \"countries\" VALUES('HR','CROATIA (local name: Hrvatska)');"
					+ "INSERT INTO \"countries\" VALUES('CU','CUBA');"
					+ "INSERT INTO \"countries\" VALUES('CY','CYPRUS');"
					+ "INSERT INTO \"countries\" VALUES('CZ','CZECH REPUBLIC');"
					+ "INSERT INTO \"countries\" VALUES('DK','DENMARK');"
					+ "INSERT INTO \"countries\" VALUES('DJ','DJIBOUTI');"
					+ "INSERT INTO \"countries\" VALUES('DM','DOMINICA');"
					+ "INSERT INTO \"countries\" VALUES('DO','DOMINICAN REPUBLIC');"
					+ "INSERT INTO \"countries\" VALUES('TP','EAST TIMOR');"
					+ "INSERT INTO \"countries\" VALUES('EC','ECUADOR');"
					+ "INSERT INTO \"countries\" VALUES('EG','EGYPT');"
					+ "INSERT INTO \"countries\" VALUES('SV','EL SALVADOR');"
					+ "INSERT INTO \"countries\" VALUES('GQ','EQUATORIAL GUINEA');"
					+ "INSERT INTO \"countries\" VALUES('ER','ERITREA');"
					+ "INSERT INTO \"countries\" VALUES('EE','ESTONIA');"
					+ "INSERT INTO \"countries\" VALUES('ET','ETHIOPIA');"
					+ "INSERT INTO \"countries\" VALUES('FK','FALKLAND ISLANDS (MALVINAS)');"
					+ "INSERT INTO \"countries\" VALUES('FO','FAROE ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('FJ','FIJI');"
					+ "INSERT INTO \"countries\" VALUES('FI','FINLAND');"
					+ "INSERT INTO \"countries\" VALUES('FR','FRANCE');"
					+ "INSERT INTO \"countries\" VALUES('FX','FRANCE, METROPOLITAN');"
					+ "INSERT INTO \"countries\" VALUES('GF','FRENCH GUIANA');"
					+ "INSERT INTO \"countries\" VALUES('PF','FRENCH POLYNESIA');"
					+ "INSERT INTO \"countries\" VALUES('TF','FRENCH SOUTHERN TERRITORIES');"
					+ "INSERT INTO \"countries\" VALUES('GA','GABON');"
					+ "INSERT INTO \"countries\" VALUES('GM','GAMBIA');"
					+ "INSERT INTO \"countries\" VALUES('GE','GEORGIA');"
					+ "INSERT INTO \"countries\" VALUES('DE','GERMANY');"
					+ "INSERT INTO \"countries\" VALUES('GH','GHANA');"
					+ "INSERT INTO \"countries\" VALUES('GI','GIBRALTAR');"
					+ "INSERT INTO \"countries\" VALUES('GR','GREECE');"
					+ "INSERT INTO \"countries\" VALUES('GL','GREENLAND');"
					+ "INSERT INTO \"countries\" VALUES('GD','GRENADA');"
					+ "INSERT INTO \"countries\" VALUES('GP','GUADELOUPE');"
					+ "INSERT INTO \"countries\" VALUES('GU','GUAM');"
					+ "INSERT INTO \"countries\" VALUES('GT','GUATEMALA');"
					+ "INSERT INTO \"countries\" VALUES('GN','GUINEA');"
					+ "INSERT INTO \"countries\" VALUES('GW','GUINEA-BISSAU');"
					+ "INSERT INTO \"countries\" VALUES('GY','GUYANA');"
					+ "INSERT INTO \"countries\" VALUES('HT','HAITI');"
					+ "INSERT INTO \"countries\" VALUES('HM','HEARD AND MC DONALD ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('VA','HOLY SEE (VATICAN CITY STATE)');"
					+ "INSERT INTO \"countries\" VALUES('HN','HONDURAS');"
					+ "INSERT INTO \"countries\" VALUES('HK','HONG KONG');"
					+ "INSERT INTO \"countries\" VALUES('HU','HUNGARY');"
					+ "INSERT INTO \"countries\" VALUES('IS','ICELAND');"
					+ "INSERT INTO \"countries\" VALUES('IN','INDIA');"
					+ "INSERT INTO \"countries\" VALUES('ID','INDONESIA');"
					+ "INSERT INTO \"countries\" VALUES('IR','IRAN (ISLAMIC REPUBLIC OF)');"
					+ "INSERT INTO \"countries\" VALUES('IQ','IRAQ');"
					+ "INSERT INTO \"countries\" VALUES('IE','IRELAND');"
					+ "INSERT INTO \"countries\" VALUES('IL','ISRAEL');"
					+ "INSERT INTO \"countries\" VALUES('IT','ITALY');"
					+ "INSERT INTO \"countries\" VALUES('JM','JAMAICA');"
					+ "INSERT INTO \"countries\" VALUES('JP','JAPAN');"
					+ "INSERT INTO \"countries\" VALUES('JO','JORDAN');"
					+ "INSERT INTO \"countries\" VALUES('KZ','KAZAKHSTAN');"
					+ "INSERT INTO \"countries\" VALUES('KE','KENYA');"
					+ "INSERT INTO \"countries\" VALUES('KI','KIRIBATI');"
					+ "INSERT INTO \"countries\" VALUES('KP','KOREA, D.P.R.O.');"
					+ "INSERT INTO \"countries\" VALUES('KR','KOREA, REPUBLIC OF');"
					+ "INSERT INTO \"countries\" VALUES('KW','KUWAIT');"
					+ "INSERT INTO \"countries\" VALUES('KG','KYRGYZSTAN');"
					+ "INSERT INTO \"countries\" VALUES('LA','LAOS ');"
					+ "INSERT INTO \"countries\" VALUES('LV','LATVIA');"
					+ "INSERT INTO \"countries\" VALUES('LB','LEBANON');"
					+ "INSERT INTO \"countries\" VALUES('LS','LESOTHO');"
					+ "INSERT INTO \"countries\" VALUES('LR','LIBERIA');"
					+ "INSERT INTO \"countries\" VALUES('LY','LIBYAN ARAB JAMAHIRIYA');"
					+ "INSERT INTO \"countries\" VALUES('LI','LIECHTENSTEIN');"
					+ "INSERT INTO \"countries\" VALUES('LT','LITHUANIA');"
					+ "INSERT INTO \"countries\" VALUES('LU','LUXEMBOURG');"
					+ "INSERT INTO \"countries\" VALUES('MO','MACAU');"
					+ "INSERT INTO \"countries\" VALUES('MK','MACEDONIA');"
					+ "INSERT INTO \"countries\" VALUES('MG','MADAGASCAR');"
					+ "INSERT INTO \"countries\" VALUES('MW','MALAWI');"
					+ "INSERT INTO \"countries\" VALUES('MY','MALAYSIA');"
					+ "INSERT INTO \"countries\" VALUES('MV','MALDIVES');"
					+ "INSERT INTO \"countries\" VALUES('ML','MALI');"
					+ "INSERT INTO \"countries\" VALUES('MT','MALTA');"
					+ "INSERT INTO \"countries\" VALUES('MH','MARSHALL ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('MQ','MARTINIQUE');"
					+ "INSERT INTO \"countries\" VALUES('MR','MAURITANIA');"
					+ "INSERT INTO \"countries\" VALUES('MU','MAURITIUS');"
					+ "INSERT INTO \"countries\" VALUES('YT','MAYOTTE');"
					+ "INSERT INTO \"countries\" VALUES('MX','MEXICO');"
					+ "INSERT INTO \"countries\" VALUES('FM','MICRONESIA, FEDERATED STATES OF');"
					+ "INSERT INTO \"countries\" VALUES('MD','MOLDOVA, REPUBLIC OF');"
					+ "INSERT INTO \"countries\" VALUES('MC','MONACO');"
					+ "INSERT INTO \"countries\" VALUES('MN','MONGOLIA');"
					+ "INSERT INTO \"countries\" VALUES('ME','MONTENEGRO');"
					+ "INSERT INTO \"countries\" VALUES('MS','MONTSERRAT');"
					+ "INSERT INTO \"countries\" VALUES('MA','MOROCCO');"
					+ "INSERT INTO \"countries\" VALUES('MZ','MOZAMBIQUE');"
					+ "INSERT INTO \"countries\" VALUES('MM','MYANMAR (Burma) ');"
					+ "INSERT INTO \"countries\" VALUES('NA','NAMIBIA');"
					+ "INSERT INTO \"countries\" VALUES('NR','NAURU');"
					+ "INSERT INTO \"countries\" VALUES('NP','NEPAL');"
					+ "INSERT INTO \"countries\" VALUES('NL','NETHERLANDS');"
					+ "INSERT INTO \"countries\" VALUES('AN','NETHERLANDS ANTILLES');"
					+ "INSERT INTO \"countries\" VALUES('NC','NEW CALEDONIA');"
					+ "INSERT INTO \"countries\" VALUES('NZ','NEW ZEALAND');"
					+ "INSERT INTO \"countries\" VALUES('NI','NICARAGUA');"
					+ "INSERT INTO \"countries\" VALUES('NE','NIGER');"
					+ "INSERT INTO \"countries\" VALUES('NG','NIGERIA');"
					+ "INSERT INTO \"countries\" VALUES('NU','NIUE');"
					+ "INSERT INTO \"countries\" VALUES('NF','NORFOLK ISLAND');"
					+ "INSERT INTO \"countries\" VALUES('MP','NORTHERN MARIANA ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('NO','NORWAY');"
					+ "INSERT INTO \"countries\" VALUES('OM','OMAN');"
					+ "INSERT INTO \"countries\" VALUES('PK','PAKISTAN');"
					+ "INSERT INTO \"countries\" VALUES('PW','PALAU');"
					+ "INSERT INTO \"countries\" VALUES('PA','PANAMA');"
					+ "INSERT INTO \"countries\" VALUES('PG','PAPUA NEW GUINEA');"
					+ "INSERT INTO \"countries\" VALUES('PY','PARAGUAY');"
					+ "INSERT INTO \"countries\" VALUES('PE','PERU');"
					+ "INSERT INTO \"countries\" VALUES('PH','PHILIPPINES');"
					+ "INSERT INTO \"countries\" VALUES('PN','PITCAIRN');"
					+ "INSERT INTO \"countries\" VALUES('PL','POLAND');"
					+ "INSERT INTO \"countries\" VALUES('PT','PORTUGAL');"
					+ "INSERT INTO \"countries\" VALUES('PR','PUERTO RICO');"
					+ "INSERT INTO \"countries\" VALUES('QA','QATAR');"
					+ "INSERT INTO \"countries\" VALUES('RE','REUNION');"
					+ "INSERT INTO \"countries\" VALUES('RO','ROMANIA');"
					+ "INSERT INTO \"countries\" VALUES('RU','RUSSIAN FEDERATION');"
					+ "INSERT INTO \"countries\" VALUES('RW','RWANDA');"
					+ "INSERT INTO \"countries\" VALUES('KN','SAINT KITTS AND NEVIS');"
					+ "INSERT INTO \"countries\" VALUES('LC','SAINT LUCIA');"
					+ "INSERT INTO \"countries\" VALUES('VC','SAINT VINCENT AND THE GRENADINES');"
					+ "INSERT INTO \"countries\" VALUES('WS','SAMOA');"
					+ "INSERT INTO \"countries\" VALUES('SM','SAN MARINO');"
					+ "INSERT INTO \"countries\" VALUES('ST','SAO TOME AND PRINCIPE');"
					+ "INSERT INTO \"countries\" VALUES('SA','SAUDI ARABIA');"
					+ "INSERT INTO \"countries\" VALUES('SN','SENEGAL');"
					+ "INSERT INTO \"countries\" VALUES('RS','SERBIA');"
					+ "INSERT INTO \"countries\" VALUES('SC','SEYCHELLES');"
					+ "INSERT INTO \"countries\" VALUES('SL','SIERRA LEONE');"
					+ "INSERT INTO \"countries\" VALUES('SG','SINGAPORE');"
					+ "INSERT INTO \"countries\" VALUES('SK','SLOVAKIA (Slovak Republic)');"
					+ "INSERT INTO \"countries\" VALUES('SI','SLOVENIA');"
					+ "INSERT INTO \"countries\" VALUES('SB','SOLOMON ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('SO','SOMALIA');"
					+ "INSERT INTO \"countries\" VALUES('ZA','SOUTH AFRICA');"
					+ "INSERT INTO \"countries\" VALUES('SS','SOUTH SUDAN');"
					+ "INSERT INTO \"countries\" VALUES('GS','SOUTH GEORGIA AND SOUTH S.S.');"
					+ "INSERT INTO \"countries\" VALUES('ES','SPAIN');"
					+ "INSERT INTO \"countries\" VALUES('LK','SRI LANKA');"
					+ "INSERT INTO \"countries\" VALUES('SH','ST. HELENA');"
					+ "INSERT INTO \"countries\" VALUES('PM','ST. PIERRE AND MIQUELON');"
					+ "INSERT INTO \"countries\" VALUES('SD','SUDAN');"
					+ "INSERT INTO \"countries\" VALUES('SR','SURINAME');"
					+ "INSERT INTO \"countries\" VALUES('SJ','SVALBARD AND JAN MAYEN ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('SZ','SWAZILAND');"
					+ "INSERT INTO \"countries\" VALUES('SE','SWEDEN');"
					+ "INSERT INTO \"countries\" VALUES('CH','SWITZERLAND');"
					+ "INSERT INTO \"countries\" VALUES('SY','SYRIAN ARAB REPUBLIC');"
					+ "INSERT INTO \"countries\" VALUES('TW','TAIWAN, PROVINCE OF CHINA');"
					+ "INSERT INTO \"countries\" VALUES('TJ','TAJIKISTAN');"
					+ "INSERT INTO \"countries\" VALUES('TZ','TANZANIA, UNITED REPUBLIC OF');"
					+ "INSERT INTO \"countries\" VALUES('TH','THAILAND');"
					+ "INSERT INTO \"countries\" VALUES('TG','TOGO');"
					+ "INSERT INTO \"countries\" VALUES('TK','TOKELAU');"
					+ "INSERT INTO \"countries\" VALUES('TO','TONGA');"
					+ "INSERT INTO \"countries\" VALUES('TT','TRINIDAD AND TOBAGO');"
					+ "INSERT INTO \"countries\" VALUES('TN','TUNISIA');"
					+ "INSERT INTO \"countries\" VALUES('TR','TURKEY');"
					+ "INSERT INTO \"countries\" VALUES('TM','TURKMENISTAN');"
					+ "INSERT INTO \"countries\" VALUES('TC','TURKS AND CAICOS ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('TV','TUVALU');"
					+ "INSERT INTO \"countries\" VALUES('UG','UGANDA');"
					+ "INSERT INTO \"countries\" VALUES('UA','UKRAINE');"
					+ "INSERT INTO \"countries\" VALUES('AE','UNITED ARAB EMIRATES');"
					+ "INSERT INTO \"countries\" VALUES('GB','UNITED KINGDOM');"
					+ "INSERT INTO \"countries\" VALUES('US','UNITED STATES');"
					+ "INSERT INTO \"countries\" VALUES('UM','U.S. MINOR ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('UY','URUGUAY');"
					+ "INSERT INTO \"countries\" VALUES('UZ','UZBEKISTAN');"
					+ "INSERT INTO \"countries\" VALUES('VU','VANUATU');"
					+ "INSERT INTO \"countries\" VALUES('VE','VENEZUELA');"
					+ "INSERT INTO \"countries\" VALUES('VN','VIET NAM');"
					+ "INSERT INTO \"countries\" VALUES('VG','VIRGIN ISLANDS (BRITISH)');"
					+ "INSERT INTO \"countries\" VALUES('VI','VIRGIN ISLANDS (U.S.)');"
					+ "INSERT INTO \"countries\" VALUES('WF','WALLIS AND FUTUNA ISLANDS');"
					+ "INSERT INTO \"countries\" VALUES('EH','WESTERN SAHARA');"
					+ "INSERT INTO \"countries\" VALUES('YE','YEMEN');"
					+ "INSERT INTO \"countries\" VALUES('ZM','ZAMBIA');"
					+ "INSERT INTO \"countries\" VALUES('ZW','ZIMBABWE');"
					+ "INSERT INTO \"countries\" VALUES('YU', 'YUGOSLAVIA');"
					+ "INSERT INTO \"countries\" VALUES('YU', 'Jugoslavien');");
			st.addBatch("COMMIT;");
			
			st.executeBatch();
		} catch (SQLException ex) {
			Log.e(TAG, "Failed to create the database: " + ex.getMessage());
			return false;
		}
		
		return true;
	}
	
}
